sonar.projectKey=Josey34_instagram-clone
sonar.organization=josey34

sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,.next/**
sonar.sourceEncoding=UTF-8

sonar.javascript.exclusions=**/node_modules/**
